In [ ]:
# Using NumPy python library, used for working with arrays
# Note: Array object in numpy is called ndarrray.

# 0-D Array
#Program1: Declare, Initialize and Display 0-D Array

# 1-D Array
#Program2: Declare, Initialize and Display 1-D Array
#Program3: Array Slicing
#Program4: Sum of array elements

# 2-D Array
#Program5: Declare, Initialize and Display 2-D Array

# 3-D Array
#Program6: Declare, Initialize and Display 3-D Array
#Program7: Declare, Initialize and Display 3-D Array

# Arrays Practical Programs
# 1. Create an 1-D integer array by accepting the size and elements from user, and display the same
# 2. Create an 2-D integer array by accepting the size and elements from user, and display the same
# 3. Create an 1-D integer array and perform operations on arrays using numpy methods such as
	# 1. sorting the array in ascending and descending order
	# 2. Finding the minimum element from an array
	# 3. Finding the maximum element from an array
	# 4. Finding the average element from an array

# 4. Create an 2-D integer array by accepting the size and element from user
	#and perform operations on arrays using numpy methods such as
	# 1. sorting the array
	# 2. Finding the minimum element from an array
	# 3. Finding the maximum element from an array
	# 4. Finding the average element from an array

# 5. Create two 2-D arrays and concatenate them on an axis
# 6. Create two 3-D arrays and concatenate them on an axis
# 7. Transpose of matrix using numpy transpose() function
# 8. Multiplication of matrix using numpy pre-define function dot() e.g.=> arr1.dot(arr2)


In [6]:
#Program1: Declared, Initialize and Display 0-D Array

#Import statement
import numpy as np

# Creating 0-D Array (Note: np.array() function is having rounded bracket not the square bracket)
arr = np.array(65)
print(arr)
arr

65


array(65)

In [7]:
#Program2: Declared, Initialize and Display 1-D Array

#Import
import numpy as np

#Creating 1-Array, (Note: np.array([]) functin is having square bracket inside rounded bracket)
arr = np.array([11,12,13,14,15])
print(arr)
arr


[11 12 13 14 15]


array([11, 12, 13, 14, 15])

In [8]:
# 1-D Array
#Program3: Array Slicing (Slicing in python means taking element from one given index to another given index.)

#import
import numpy as np
arr = np.array([11,12,13,14,15,16,17,18])

#Array slicing
#Displaying the array element from 1st to 3rd index
print(arr[1:4])

#Displaying the Array element from beginning to 3rd index
print(arr[:4])

#Displaying the Array elemetns from 3rd index
print(arr[3:])


[12 13 14]
[11 12 13 14]
[14 15 16 17 18]


In [14]:
# 1-D Array
#Program4: Sum of array elements

#import
import numpy as np

arr = np.array([11,12,13,14,15,16])

#Sum of two array element
print(arr[0] + arr[4])

#Sum of entire array, using pre-defined method
print(arr.sum())

#Sum of entrie array, using logic
sum = 0
for i in arr:
    sum = sum + i
print("Array Sum:", sum)


26
81
Array Sum: 81


In [56]:
# 2-D Array
#Program5: Declared, Initialize and Display 2-D Array

import numpy as np

#Declaring 2-D Array (Note: The array declaration staring from two square bracket [[ is 2-D Array)
arr = np.array([[11,12,13,14], [101,102,103,104]])

#Displaying entire 2-D array
print(arr)

#Display the specific element of an array

#Displaying the 0th row, 2nd element
#Method 1:
print("\nMethod 1: ", arr[0,1])

#Method 2:
print("Method 2: ", arr[0][1])

#Displaying 1st row 4th element
print(arr[1][3])


[[ 11  12  13  14]
 [101 102 103 104]]

Method 1:  12
Method 2:  12
104


In [16]:
# 3-D Array
#Program6: Declare, Initialize and Display 3-D Array

import numpy as np

#3-D array having only one layer i.e 0th layer
arr = np.array([[[11,12,13], [101,102,103], [1001,1002,1003]]])

print(arr)
arr

print("\nDisplaying specific element of the array")

#Note:
#Here, 0 -> mean 0th Layer, Given array is having one layer only so the entire row is 0th layer
#Here, 1 -> 0th layer index 1 bracket, i.e [101,102,103]
#Here, 2 -> 0th layer index 1 bracket 2nd index element i.e. 103
print(arr[0,1,2])


[[[  11   12   13]
  [ 101  102  103]
  [1001 1002 1003]]]

Displaying specific element of the array
103


In [15]:
# 3-D Array
#Program7: Declare, Initialize and Display 3-D Array

import numpy as np

#3-D array having only two layers i.e 0th and 1st layer
arr = np.array([
                [ [1,2,3], [11,12,13], [101,102,103] ], 
                [ [111,112,113], [1101,1102,1103], [11001,11002,11003] ]
                ])

print(arr)
arr

print("\nDisplaying specific element of the array")

#Note:
#Here, 1 -> mean 1st Layer, Given array is having two layer.
#Here, 2 -> 1st layer index 2 bracket, i.e [11001,11002,11003]
#Here, 2 -> 0th layer index 2 bracket 2nd index element i.e. 11003
print(arr[1,2,2])


[[[    1     2     3]
  [   11    12    13]
  [  101   102   103]]

 [[  111   112   113]
  [ 1101  1102  1103]
  [11001 11002 11003]]]

Displaying specific element of the array
11003


In [33]:
#Joining Arrays
#Program8: Joining two 1-D Arrays

import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

#Concatenating/Joining two arrays
arr = np.concatenate((arr1,arr2))

#Displaying the concatenated array
print("\nJoining two arrays:")
print(arr)

#Here we joing 2 array by using + operator which does the sum of their elements
print("\nArray 1:",arr1)
print("Array 2:", arr2)
arr = arr1+arr2
print("Sum of Arr1 and Arr2:", arr)



Joining two arrays:
[1 2 3 4 5 6 7 8]

Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Sum of Arr1 and Arr2: [ 6  8 10 12]


In [45]:
# Arrays Practical Programs
# 1. Create an 1-D integer array by accepting the size and elements from user, and display the same

#import
import numpy as np

#Accept size
num = int(input("Enter Array size: "))

#Create integer type Array with user defined size
#Note: dtype by default is float
arr = np.ndarray(shape=(num), dtype=int)

#Accept array elements from user
for i in range(num):
    arr[i] = input("Enter elements: ")

print(arr)


[ 1.2  5.   8.  98. ]


In [60]:
# Arrays Practical Programs
# 2. Create an 2-D integer array by accepting the size and elements from user, and display the same

import numpy as np

#Accept 2-D Array size for number of rows and column
rows = int(input("Enter Total Rows:"))
cols = int(input("Enter Total columns: "))

#Create an 2-D integer arrays
arr = np.ndarray(shape=(rows,cols), dtype=int)

#Accept elements
for r in range(rows):
    for c in range(cols):
        arr[r][c] = input("Enter elements: ")

print("Displaying 2-D Array:")
arr


Displaying 2-D Array:


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
# Arrays Practical Programs
# 3. Create an 1-D integer array by accepting size and element from user 
	#and perform operations on arrays using numpy methods such as
	# 1. sorting the array in ascending and descending order
	# 2. Finding the minimum element from an array
	# 3. Finding the maximum element from an array
	# 4. Finding the average element from an array

import numpy as np

#Accept size
size = int(input("Enter Size: "))

#Create array
arr = np.ndarray(shape=(size), dtype=int)

#Enter Elements
for i in range(size):
	print("Enter Element",i+1)
	arr[i] = input()

print("Entire Array:", arr)

#Sort array in Ascending order using pre-define method
print("\nSorted Array in ASC order:", np.sort(arr))

#Sort array in descending order using pre-define method
print("Sorted Array in DSC order: ", np.sort(arr)[::-1])

#Find sum,min,max,average of all array element usig pre-defined method
print("\nSum of all element:", np.sum(arr))
print("Min element:", np.min(arr))
print("Max element:", np.max(arr))
print("Avg element:", np.average(arr))


Enter Element 1
Enter Element 2
Enter Element 3
Enter Element 4
Entire Array: [98 96  2 16]

Sorted Array in ASC order: [ 2 16 96 98]
Sorted Array in DSC order:  [98 96 16  2]

Sum of all element: 212
Min element: 2
Max element: 98
Avg element: 53.0


In [84]:
# Arrays Practical Programs
# 4. Create an 2-D integer array by accepting the size and element from user
	#and perform operations on arrays using numpy methods such as
	# 1. sorting the array
	# 2. Finding the minimum element from an array
	# 3. Finding the maximum element from an array
	# 4. Finding the average element from an array

import numpy as np

rows = int(input("Total rows: "))
cols = int(input("Total cols: "))

#Create an 2-D array
arr = np.ndarray(shape=(rows,cols), dtype=int)

#Accept elements
for r in range(rows):
	for c in range(cols):
		arr[r][c] = input("Enter Element: ")

print("Array: \n", arr)

#Sort the array
# Note: Here sort method sort each and every rows, not a entire arrays in ascending order
print("\nSorted array:\n", np.sort(arr))

#Find sum, min, max, average of 2-D Array using pre-define method
print("\nSum of array: ", np.sum(arr))
print("Min of array:", np.min(arr))
print("Max of array: ", np.max(arr))
print("Average of array: ", np.average(arr))


Array: 
 [[ 1  4]
 [19 98]]

Sorted array:
 [[ 1  4]
 [19 98]]

Sum of array:  122
Min of array: 1
Max of array:  98
Average of array:  30.5


In [71]:
# Arrays Practical Programs
# 5. Create two 2-D arrays and concatenate them on an axis

import numpy as np

arr1=np.array( [ [11,12], [13,14] ])
arr2=np.array( [ [10,20],[30,40] ] )

print("Array 1: ")
print(arr1)

print("\nArray 2: ")
print(arr2)

# concatination of arr1 & arr2 with axis = 1
arr3 = np.concatenate((arr1, arr2), axis=1)
print("\nArray 3 with axis 1: ") 
print(arr3)

# concatination of arr1 & arr2 with axis = 0
arr3 = np.concatenate((arr1, arr2), axis=0)
print("\nArray 3 with axis 0: ") 
print(arr3)


Array 1: 
[[11 12]
 [13 14]]

Array 2: 
[[10 20]
 [30 40]]

Array 3 with axis 1: 
[[11 12 10 20]
 [13 14 30 40]]

Array 3 with axis 0: 
[[11 12]
 [13 14]
 [10 20]
 [30 40]]


In [82]:
# Arrays Practice Program
# 6. Create two 3-D arrays and concatenate them on an axis

import numpy as np

arr1 = np.array([[[10,20,30], [40,50,60], [70,80,90]]])
arr2 = np.array([[[210,220,230], [240,250,260], [270,280,290]]])

print("Array1: ",arr1)

print("\nArray2: ",arr2)

# concatination of arr1 & arr2 with axis = 1
arr3 = np.concatenate((arr1, arr2), axis=2)
print("\nArray 3 with axis 1: ") 
print(arr3)


Array1:  [[[10 20 30]
  [40 50 60]
  [70 80 90]]]

Array2:  [[[210 220 230]
  [240 250 260]
  [270 280 290]]]

Array 3 with axis 1: 
[[[ 10  20  30 210 220 230]
  [ 40  50  60 240 250 260]
  [ 70  80  90 270 280 290]]]


In [98]:
# 2-D Array
# 7. Transpose of matrix

import numpy as np

arr = np.array([[11,12,13], [101,102,103], [110, 120, 130]])

print("Actual Matrix:\n",arr)

#Transpose of matrix
print("\nMatrix Transpose: \n", np.transpose(arr))


Actual Matrix:
 [[ 11  12  13]
 [101 102 103]
 [110 120 130]]

Matrix Transpose: 
 [[ 11 101 110]
 [ 12 102 120]
 [ 13 103 130]]


In [101]:
# 2-D Array
# 8. Multiplication of Matrix using pre-define numpy method

import numpy as np

arr1 = np.array([[2,4], [6,8]])
arr2 = np.array([[5,8], [12,18]])

print("Array 1: \n", arr1)
print("\nArray 2: \n", arr2)

#Multiplication of arr1 X arr2
arr3 = arr1.dot(arr2)
print("\nMultiplication of arr1 X arr2: \n", arr3)


Array 1: 
 [[2 4]
 [6 8]]

Array 2: 
 [[ 5  8]
 [12 18]]

Multiplication of arr1 X arr2: 
 [[ 58  88]
 [126 192]]
